# Generated by Django 5.1.2 on 2025-07-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loaction',
            new_name='location',
        ),
    ]
